# permissions for end users to edit scvmmpersistentdisks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-scvmm
    app.kubernetes.io/managed-by: kustomize
  name: scvmmpersistentdisk-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - scvmmpersistentdisks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - scvmmpersistentdisks/status
  verbs:
  - get
