apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ScvmmPersistentDisk
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-scvmm
    app.kubernetes.io/managed-by: kustomize
  name: scvmmpersistentdisk-sample
spec:
  # TODO(user): Add fields here
